"""tao bang inbox

Revision ID: 39bb3f77bcc4
Revises: d37670ffe9d4
Create Date: 2026-07-25 16:14:55.929320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39bb3f77bcc4"
down_revision: Union[str, Sequence[str], None] = "d37670ffe9d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("external_channel_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("credential", sa.Text(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('ZALO', 'FACEBOOK', 'INSTAGRAM')", name="ck_channel_platform_hop_le"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_channel_department_id", "channels", ["department_id"], unique=False)
    op.create_index("ix_channel_is_active", "channels", ["is_active"], unique=False)
    op.create_index(
        "uq_channel_platform_external", "channels", ["platform", "external_channel_id"], unique=True
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_customer_channel_external", "customers", ["channel_id", "external_id"], unique=True
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CHO_PHAN', 'DANG_MO', 'DA_DONG')", name="ck_conversation_status_hop_le"
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_conversation_channel_id", "conversations", ["channel_id"], unique=False)
    op.create_index("ix_conversation_customer_id", "conversations", ["customer_id"], unique=False)
    op.create_index(
        "ix_conversation_department_id", "conversations", ["department_id"], unique=False
    )
    op.create_index(
        "ix_conversation_last_message_at",
        "conversations",
        [sa.literal_column("last_message_at DESC")],
        unique=False,
    )
    op.create_index("ix_conversation_status", "conversations", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("external_message_id", sa.String(length=255), nullable=True),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('INBOUND', 'OUTBOUND')", name="ck_message_direction_hop_le"
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_message_conversation_id", "messages", ["conversation_id", "created_at"], unique=False
    )
    op.create_index(
        "uq_message_external_id",
        "messages",
        ["external_message_id"],
        unique=True,
        postgresql_where=sa.text("external_message_id IS NOT NULL"),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("stored_path", sa.String(length=1000), nullable=False),
        sa.Column("original_url", sa.String(length=1000), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('IMAGE', 'FILE')", name="ck_attachment_kind_hop_le"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_attachment_message_id", "attachments", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachment_message_id", table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(
        "uq_message_external_id",
        table_name="messages",
        postgresql_where=sa.text("external_message_id IS NOT NULL"),
    )
    op.drop_index("ix_message_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_conversation_status", table_name="conversations")
    op.drop_index("ix_conversation_last_message_at", table_name="conversations")
    op.drop_index("ix_conversation_department_id", table_name="conversations")
    op.drop_index("ix_conversation_customer_id", table_name="conversations")
    op.drop_index("ix_conversation_channel_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("uq_customer_channel_external", table_name="customers")
    op.drop_table("customers")
    op.drop_index("uq_channel_platform_external", table_name="channels")
    op.drop_index("ix_channel_is_active", table_name="channels")
    op.drop_index("ix_channel_department_id", table_name="channels")
    op.drop_table("channels")
    # ### end Alembic commands ###
