"""tao bang identity

Revision ID: d37670ffe9d4
Revises: 
Create Date: 2026-07-24 03:54:20.549440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd37670ffe9d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_department_is_active', 'departments', ['is_active'], unique=False)
    op.create_index('uq_department_name', 'departments', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'ADMIN' AND department_id IS NULL) OR (role IN ('STAFF', 'MANAGER') AND department_id IS NOT NULL)", name='ck_user_phong_ban_khop_vai_tro'),
    sa.CheckConstraint("role IN ('STAFF', 'MANAGER', 'ADMIN')", name='ck_user_role_hop_le'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_department_id', 'users', ['department_id'], unique=False)
    op.create_index('ix_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('uq_department_active_manager', 'users', ['department_id'], unique=True, postgresql_where=sa.text("role = 'MANAGER' AND is_active"))
    op.create_index('uq_user_email', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_log_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_log_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_log_resource', table_name='audit_logs')
    op.drop_index('ix_audit_log_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_log_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_log_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_user_email', table_name='users')
    op.drop_index('uq_department_active_manager', table_name='users', postgresql_where=sa.text("role = 'MANAGER' AND is_active"))
    op.drop_index('ix_user_is_active', table_name='users')
    op.drop_index('ix_user_department_id', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_department_name', table_name='departments')
    op.drop_index('ix_department_is_active', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
