"""tao bang keyword

Revision ID: dff8571b18ef
Revises: fe6983156947
Create Date: 2026-07-29 10:42:03.405060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff8571b18ef'
down_revision: Union[str, Sequence[str], None] = 'fe6983156947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_department_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_analysis_conversation_id', 'conversation_analyses', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_analysis_suggested_department_id', 'conversation_analyses', ['suggested_department_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('normalized', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keyword_department_id', 'keywords', ['department_id'], unique=False)
    op.create_index('uq_keyword_department_normalized', 'keywords', ['department_id', 'normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_keyword_department_normalized', table_name='keywords')
    op.drop_index('ix_keyword_department_id', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_conversation_analysis_suggested_department_id', table_name='conversation_analyses')
    op.drop_index('ix_conversation_analysis_conversation_id', table_name='conversation_analyses')
    op.drop_table('conversation_analyses')
    # ### end Alembic commands ###
