"""tao bang hrm

Revision ID: fe6983156947
Revises: 39bb3f77bcc4
Create Date: 2026-07-28 10:01:11.660098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe6983156947"
down_revision: Union[str, Sequence[str], None] = "39bb3f77bcc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("metric_type", sa.String(length=40), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subject_type IN ('USER', 'DEPARTMENT')", name="ck_kpi_target_subject_type_hop_le"
        ),
        sa.CheckConstraint("period_month BETWEEN 1 AND 12", name="ck_kpi_target_month_hop_le"),
        sa.CheckConstraint("target_value >= 0", name="ck_kpi_target_value_khong_am"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_kpi_target_department_id", "kpi_targets", ["department_id"], unique=False)
    op.create_index(
        "uq_kpi_target_subject_metric_period",
        "kpi_targets",
        ["subject_type", "subject_id", "metric_type", "period_year", "period_month"],
        unique=True,
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("request_type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("leave_start", sa.Date(), nullable=True),
        sa.Column("leave_end", sa.Date(), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "request_type IN ('NGHI_PHEP', 'TANG_LUONG', 'KHAC')", name="ck_request_type_hop_le"
        ),
        sa.CheckConstraint(
            "status IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI', 'DA_HUY')",
            name="ck_request_status_hop_le",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_request_department_id", "requests", ["department_id"], unique=False)
    op.create_index("ix_request_requester_id", "requests", ["requester_id"], unique=False)
    op.create_index("ix_request_status", "requests", ["status"], unique=False)
    op.create_table(
        "shifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_time > start_time", name="ck_shift_window_hop_le"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_shift_department_id", "shifts", ["department_id"], unique=False)
    op.create_index("ix_shift_is_active", "shifts", ["is_active"], unique=False)
    op.create_table(
        "shift_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'CANCELLED')", name="ck_shift_assignment_status_hop_le"
        ),
        sa.CheckConstraint("end_time > start_time", name="ck_shift_assignment_window_hop_le"),
        sa.ForeignKeyConstraint(["shift_id"], ["shifts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_shift_assignment_department_id", "shift_assignments", ["department_id"], unique=False
    )
    op.create_index("ix_shift_assignment_shift_id", "shift_assignments", ["shift_id"], unique=False)
    op.create_index(
        "ix_shift_assignment_user_date", "shift_assignments", ["user_id", "work_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shift_assignment_user_date", table_name="shift_assignments")
    op.drop_index("ix_shift_assignment_shift_id", table_name="shift_assignments")
    op.drop_index("ix_shift_assignment_department_id", table_name="shift_assignments")
    op.drop_table("shift_assignments")
    op.drop_index("ix_shift_is_active", table_name="shifts")
    op.drop_index("ix_shift_department_id", table_name="shifts")
    op.drop_table("shifts")
    op.drop_index("ix_request_status", table_name="requests")
    op.drop_index("ix_request_requester_id", table_name="requests")
    op.drop_index("ix_request_department_id", table_name="requests")
    op.drop_table("requests")
    op.drop_index("uq_kpi_target_subject_metric_period", table_name="kpi_targets")
    op.drop_index("ix_kpi_target_department_id", table_name="kpi_targets")
    op.drop_table("kpi_targets")
    # ### end Alembic commands ###
